package com.masrofy.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.compositeOver
import androidx.compose.ui.graphics.toArgb

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val ColorTotalIncome = Color(0xFF21AB51)
val ColorTotalExpense = Color(0xFFFF3F3F)




val md_theme_light_primary = Color(0xFF8D4F00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCC0)
val md_theme_light_onPrimaryContainer = Color(0xFF2D1600)
val md_theme_light_secondary = Color(0xFF735943)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCC0)
val md_theme_light_onSecondaryContainer = Color(0xFF291806)
val md_theme_light_tertiary = Color(0xFF596239)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDEE8B3)
val md_theme_light_onTertiaryContainer = Color(0xFF171E00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201B17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201B17)
val md_theme_light_surfaceVariant = Color(0xFFF2DFD1)
val md_theme_light_onSurfaceVariant = Color(0xFF51443A)
val md_theme_light_outline = Color(0xFF837469)
val md_theme_light_inverseOnSurface = Color(0xFFFAEFE7)
val md_theme_light_inverseSurface = Color(0xFF352F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB875)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8D4F00)
val md_theme_light_outlineVariant = Color(0xFFD5C3B6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB875)
val md_theme_dark_onPrimary = Color(0xFF4B2800)
val md_theme_dark_primaryContainer = Color(0xFF6B3B00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC0)
val md_theme_dark_secondary = Color(0xFFE2C0A4)
val md_theme_dark_onSecondary = Color(0xFF412C19)
val md_theme_dark_secondaryContainer = Color(0xFF59422D)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCC0)
val md_theme_dark_tertiary = Color(0xFFC2CC99)
val md_theme_dark_onTertiary = Color(0xFF2C340F)
val md_theme_dark_tertiaryContainer = Color(0xFF424A23)
val md_theme_dark_onTertiaryContainer = Color(0xFFDEE8B3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201B17)
val md_theme_dark_onBackground = Color(0xFFECE0D9)
val md_theme_dark_surface = Color(0xFF201B17)
val md_theme_dark_onSurface = Color(0xFFECE0D9)
val md_theme_dark_surfaceVariant = Color(0xFF51443A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C3B6)
val md_theme_dark_outline = Color(0xFF9E8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF201B17)
val md_theme_dark_inverseSurface = Color(0xFFECE0D9)
val md_theme_dark_inversePrimary = Color(0xFF8D4F00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB875)
val md_theme_dark_outlineVariant = Color(0xFF51443A)
val md_theme_dark_scrim = Color(0xFF000000)

val surface2Light = Color(md_theme_light_primary.copy(alpha = 0.08f).toArgb())
    .compositeOver(
    md_theme_light_surface)
val seed = Color(0xFF00677D)
